name = "osado-admin"
compatibility_date = "2024-09-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"

[build.environment]
NODE_VERSION = "18"